apiVersion: v1
data:
  Secret: eyJhbGciOiJFUzM4NCIsImtpZCI6IiJ9.XAAAAAVjb25uZWN0b3JfaWQAEAAAAAAAAAAAAAAAAAAAAAAAAAAABXNpdGVfaWQAEAAAAAAMXOXlKOFGprneNNFbag-1EGludGVybmFsX3NpdGVfaWQAOA8AAAA.NJ8XnEmDaFoljtgrjXj9Ze-ACyTgT3xN8XLztkxteTXdH2bVc5H3h-o1bSP99lHBngRQ7VGr3lWgxkwVEHw6YrKcfyDlCMIw-dJkYkyPEJohP9W_AN6yQXt4jgjobPZd
kind: ConfigMap
metadata:
  name: cm-adanite
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: adanite
  name: adanite
spec:
  securityContext:
    sysctls:
    - name: net.ipv4.ip_forward
      value: "1"
  volumes:
  - name: dev-net-tun
    hostPath:
      path: /dev/net/tun  
  containers:
  - image: adanite/odo_connector:eu_v3
    name: odoconnector
    securityContext:
      privileged: true
      capabilities:
        add: ["NET_ADMIN"]
    volumeMounts:
    - mountPath: /dev/net/tun
      name: dev-net-tun
    env:
      # Define the environment variable
      - name: Secret
        valueFrom:
          configMapKeyRef:
            # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
            name: cm-adanite
            # Specify the key associated with the value
            key: Secret
  dnsPolicy: "None"
  dnsConfig:
    nameservers:
      - 8.8.8.8
      - 8.8.4.4
  restartPolicy: Always        
